Update FreeBSD client script to 1.4.0p21

diff --git a/templates/check_mk_agent.freebsd.j2 b/templates/check_mk_agent.freebsd.j2
--- a/templates/check_mk_agent.freebsd.j2
+++ b/templates/check_mk_agent.freebsd.j2
@@ -46,7 +46,6 @@ export MK_LIBDIR="{{ install_check_mk_client_home }}"
 export MK_CONFDIR="{{ install_check_mk_client_home }}"
 export MK_VARDIR="{{ install_check_mk_client_home }}"
 
-
 # Make sure, locally installed binaries are found
 PATH=$PATH:/usr/local/bin:/usr/local/sbin
 
@@ -106,7 +105,7 @@ function run_cached() {
 }
 
 echo '<<<check_mk>>>'
-echo Version: 1.4.0p19
+echo Version: 1.4.0p21
 echo AgentOS: freebsd
 
 
@@ -381,14 +380,18 @@ fi
 if [ -r "$MK_CONFDIR/fileinfo.cfg" ] ; then
     echo '<<<fileinfo:sep(124)>>>'
     date +%s
-    for line in $(cat "$MK_CONFDIR/fileinfo.cfg")
-    do
-        stat -f "%N|%z|%m" "$line" 2>/dev/null
 
-        if [ $? -ne 0 ]; then
-            echo "$line|missing|$(date +%s)"
-        fi
-    done
+    OLD_IFS=$IFS
+    IFS='
+'
+    while read -r pattern; do
+        case $pattern in
+            /*) for file in $pattern; do
+                    stat -f "%N|%z|%m" "$file" 2>/dev/null || echo "$file|missing|`date +%s`"
+                done ;;
+        esac
+    done < "$MK_CONFDIR/fileinfo.cfg"
+    IFS=$OLD_IFS
 fi
 
 
